rawGitContentUrl = "https://raw.githubusercontent.com/"
githubBaseUrl= "https://github.com/"
fromSearchDockerFile = "https://api.github.com/search/code?q=FROM+filename:Dockerfile+repo:"
genericGitHubUrl = "://github.com/"
githubRegEx = "(http(s)?)(:(//)?)(github.com)(/)([a-zA-Z0-9-/_]+)(\.git)$"
commitRegEx = "^[0-9a-z]{5,40}$"